title: Press Realises
email: your-email@domain.com
description: You can update description in update blog details page.

baseurl: "/"
url: http://keralahost.in/alisonaitken
google_adsense: Your-adsense-code

markdown: kramdown

name: Press Realises

date: 2019-04-22 17:55:32 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/alisonaitken/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 

author: alisonaitken
